### ISSUE TITLE
Weird look of XAML structure guide lines

### ISSUE THREAD

**Issue by mohafifi** [kai-oswald/NightOwl-VS-Theme#19] opened 2020-07-06 13:03 UTC
This theme is very nice but I am facing a problem.
Structure guide lines of C# code editor looks great like this:
![image](https://user-images.githubusercontent.com/67908893/86595801-8f1a7a00-bf99-11ea-954f-4045b148d9e0.png)

While Structure guide lines in WPF XAML documents have a weird look!

![image](https://user-images.githubusercontent.com/67908893/86595884-b07b6600-bf99-11ea-9536-5f267c7afc93.png)

Does any one know why? Or how to fix from the theme editor?

Thanks & regards
M.Afifi

**Comment by kai-oswald** [comment] 2020-07-08 07:01
Hey, 

thank you for reporting this issue. It was caused by multiple layers of the same background which were then somehow overlapped on the structure guidelines.
Removing the background colors on XAML-Files should fix this: 1b9c1ec3c4d5d86c06395016aeb2aab41f3cf191
Fixed with v0.1.10.

**Comment by mohafifi** [comment] 2020-07-08 17:12
Thanks a million.
It has been fixed.
Regards
M.Afifi

**Closed as completed** 2020-07-08 17:13 UTC
