### ISSUE TITLE
Unreadable xml file

### ISSUE THREAD

**Issue by pasqualedante** [kai-oswald/NightOwl-VS-Theme#13] opened 2020-05-02 13:30 UTC
With your (great!) theme port, I can't read the AndroidManifest.xml in a Xamarin app developed in VS 2019.

![image](https://user-images.githubusercontent.com/813690/80865441-cf076d00-8c89-11ea-8a5b-9711f3488a55.png)

It's possible to fix this?
Thanks in advance.

**Comment by kai-oswald** [comment] 2020-06-30 13:27
Hey,
thanks for reporting this issue. Should be fixed with 3c33f22 and v0.1.8.
Can you update and check if the issue is fixed?

**Comment by pasqualedante** [comment] 2020-06-30 13:45
Yep, it works like a charm.

**Closed as completed** 2020-07-01 05:48 UTC
